# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Saul Arciniega
title: Student of Development and Computing Science
email: saul.arciniega@outlook.com
website: www.github.com/pawis7

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: herepawis
github_username:  pawis7
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: paw0s
linkedin_username: pawis_7
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: "@pawis_7"
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.pixelminecraftpaw.xyz

# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  My Name is Saul, I am a Studient of Software Engineering at the "Universidad De Guadalajara" (UdG)

  I am most skilled in: <mark>Hosting Minecraft Servers</mark> and <mark>Expert Learning on whatever</mark>

  I really like to learn new things, to be updated all the time and try to understand everything, another thing that appeals to me is to reverse engineer things, otherwise, learn how everything works, learn from that and see if there is something better to do.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: My First Unity Game
        link: github.com/pawis7/MyGame
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/pawis7/MyGame---
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          I could possibly be sued if I sold it (even if I don't).
        description: | # this will include new lines to allow paragraphs
          I made this game for my hypermedia class, I learned a little bit of C# and a lot of unity, both physics and aesthetic details, for advantage I had knowledge of video game editors, the truth is that I didn't like it at all but it's done.

      - layout: top-middle
        title: WebCrawler
        link: github.com/pawis7/WebCrawler

        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/pawis7/WebCrawler
        quote: >
          I made a WebCrawler to compare prices of a product in Mercado libre and aliexpress.
        description: | # this will include new lines to allow paragraphs
          This project was made for my web programming class, this project filters the products of a page to compile all the information of the products to make easier your search.
      - layout: top-middle
        title: My Web Page
        link: pawstudio.xyz

        quote: >
          I made my web page to show my projects and my skills and to learn how to host a web page.
        description: | # this will include new lines to allow paragraphs
          I made this web page to show my projects and my skills, I learned a lot of html, javascript, nextjs, and more, I also learned how to host a web page in vercel and point my domain to it.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: I have no work experience. 
        quote: >
          I didnt have the opportunity to work in a company, but I have experience in python, javascript, html, c++ and more (U can see my projects on projects Section).
        description: | # this will include new lines to allow paragraphs


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Universidad de Guadalajara
        caption: 2022 - Now
        sub_title: "Software Engineering"
        quote: >
          This university is a fundamental institution in the formation of human resources and in the production of scientific and technological knowledge, both regionally and nationally.
        description: | # this will include new lines to allow paragraphs
          I felt that half of the career I did not learn anything since it uses half of the career to teach fundamentals and use it as a filter, however in my 5th semester I learned a lot of skills, how data mining works, how to host servers in dockers, github and above all, python.

          
          I owe my great progress to my teacher <mark>Carlos Alberto Guzman Montes</mark>, who gave me many tools of which I took the most interesting and I plan to take more in the future for my training.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Play video games like minecraft, goemetry dash, and more.
      - I want to go deeper into Geometry Dash, since I create levels here and this helps my imagination a lot.
      - Do Gym.
      - I like to learn new things, I am currently learning how to almost all by my own.

      Look My Minecraft Server and Domine: <mark>PixelMinecraftPaw</mark> 

      ![Minecraft Server](images/MinecraftServer.png)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
